build:
	go build -o ./bin/ cmd/app/main.go

run:
	go run cmd/app/main.go

migrate-up:
	migrate -path ./migrations -database 'postgres://postgres:123456@localhost:5432/schema?sslmode=disable' up

migrate-down:
	migrate -path ./migrations -database 'postgres://postgres:123456@localhost:5432/schema?sslmode=disable' down